"""Read prebuilt web payloads without reprocessing backend datasets."""

from __future__ import annotations

from functools import lru_cache
import gzip
import json
from pathlib import Path
import tomllib
from typing import Any


class WebDataService:
    """Serve immutable payloads generated by :class:`WebDataBuilder`."""

    def __init__(self, config_path: str | Path = "config/web.toml") -> None:
        path = Path(config_path).expanduser()
        if not path.is_absolute() and not path.exists():
            path = Path(__file__).resolve().parents[2] / path
        self.config_path = path.resolve()
        self.project_root = self.config_path.parent.parent
        with self.config_path.open("rb") as file:
            self.config = tomllib.load(file)
        self.output_root = self.project_root / self.config["data"]["output_root"]
        self.visits = 0

    def bootstrap(self) -> dict[str, Any]:
        """Return interface settings and the prebuilt data manifest."""

        self.visits += 1
        manifest = self._read("manifest.json.gz")
        return {
            "site": self.config["site"],
            "map": self.config["map"],
            "stages": self.config["stages"],
            "layers": self.config["layers"],
            "news": self.config.get("news", []),
            "manifest": manifest,
            "visits": self.visits,
        }

    def boundary(self, stage_id: str) -> dict[str, Any]:
        """Return the prebuilt administrative background for a map stage."""

        return self._read("boundary/common.json.gz")

    def boundary_path(self, stage_id: str) -> Path:
        """Return the immutable compressed boundary payload path."""

        return self._path("boundary/common.json.gz")

    def layer(
        self,
        stage_id: str,
        layer_id: str,
        class_name: str | None = None,
    ) -> dict[str, Any]:
        """Return one prebuilt layer, optionally selecting a resource class."""

        relative = f"layers/{stage_id}/{layer_id}"
        if layer_id == "resource":
            if class_name is None:
                raise KeyError("Resource layers require a class name.")
            source_stage = "mapping" if stage_id == "case" else stage_id
            relative = f"layers/{source_stage}/{layer_id}/{class_name}"
        return self._read(f"{relative}.json.gz")

    def layer_path(
        self,
        stage_id: str,
        layer_id: str,
        class_name: str | None = None,
    ) -> Path:
        """Return the immutable compressed layer payload path."""

        relative = f"layers/{stage_id}/{layer_id}"
        if layer_id == "resource":
            if class_name is None:
                raise KeyError("Resource layers require a class name.")
            source_stage = "mapping" if stage_id == "case" else stage_id
            relative = f"layers/{source_stage}/{layer_id}/{class_name}"
        return self._path(f"{relative}.json.gz")

    def application(self) -> dict[str, Any]:
        """Return the latest prebuilt UC plotting data."""

        return self._read("application/uc.json.gz")

    def application_path(self) -> Path:
        """Return the immutable compressed UC payload path."""

        return self._path("application/uc.json.gz")

    @lru_cache(maxsize=64)
    def _read(self, relative: str) -> dict[str, Any]:
        path = self._path(relative)
        with gzip.open(path, "rt", encoding="utf-8") as file:
            return json.load(file)

    def _path(self, relative: str) -> Path:
        path = (self.output_root / relative).resolve()
        if self.output_root.resolve() not in path.parents:
            raise KeyError("Web payload path escapes the configured output root.")
        if not path.exists():
            raise FileNotFoundError(
                f"Web data are unavailable: {path}. Run "
                "`python -m src.web.build --config config/web.toml`."
            )
        return path


def encode_json(payload: dict[str, Any]) -> bytes:
    """Encode a response consistently for the HTTP layer."""

    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode()
